CREATE TABLE `Errors` (
	`ErrorID` INT(11) NOT NULL AUTO_INCREMENT,
	`Source` VARCHAR(50) NOT NULL,
	`Message` VARCHAR(200) NOT NULL,
	`Data` VARCHAR(2000) NOT NULL,
	`RecordedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ErrorID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;