CREATE TABLE IF NOT EXISTS `nflgameinstances` (
  `InstanceID` int(11) NOT NULL AUTO_INCREMENT,
  `GameID` varchar(50) NOT NULL,
  `Date` date NOT NULL,
  `StateID` tinyint(4) NOT NULL,
  `Time` varchar(50) NOT NULL,
  `SeasonYear` varchar(50) NOT NULL,
  `SeasonType` varchar(50) NOT NULL,
  `SeasonWeek` varchar(50) NOT NULL,
  `Quarter` varchar(50) NOT NULL,
  `AwayTeamID` tinyint(4) NOT NULL,
  `AwayScore` tinyint(4) NOT NULL,
  `HomeTeamID` tinyint(4) NOT NULL,
  `HomeScore` tinyint(4) NOT NULL,
  `RecordedOn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`InstanceID`),
  KEY `FK_NFLGameInstances_StateID` (`StateID`),
  KEY `FK_NFLGameInstances_AwayTeamID` (`AwayTeamID`),
  KEY `FK_NFLGameInstances_HomeTeamID` (`HomeTeamID`),
  KEY `IX_NFLGameInstances_GameID` (`GameID`,`RecordedOn`),
  CONSTRAINT `FK_NFLGameInstances_AwayTeamID` FOREIGN KEY (`AwayTeamID`) REFERENCES `nhlteams` (`TeamID`),
  CONSTRAINT `FK_NFLGameInstances_HomeTeamID` FOREIGN KEY (`HomeTeamID`) REFERENCES `nhlteams` (`TeamID`),
  CONSTRAINT `FK_NFLGameInstances_StateID` FOREIGN KEY (`StateID`) REFERENCES `nhlstates` (`StateID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;