CREATE TABLE IF NOT EXISTS `nflteams` (
  `TeamID` tinyint(4) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `City` varchar(50) NOT NULL,
  `DisplayName` varchar(50) NOT NULL,
  `TwitterAccount` varchar(50) DEFAULT NULL,
  `TwitterHashtag` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`TeamID`),
  KEY `IX_NFLTeams` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `nflteams` (`TeamID`, `Name`, `City`, `DisplayName`, `TwitterAccount`, `TwitterHashtag`) VALUES
	(1, 'Bills', 'Buffalo', 'BUF', '@buffalobills', '#Bills'),
	(2, 'Dolphins', 'Miami', 'MIA', '@MiamiDolphins', '#Dolphins'),
	(3, 'Patriots', 'New England', 'NE', '@Patriots', '#Patriots'),
	(4, 'Jets', 'New York', 'NYJ', '@nyjets', '#Jets'),
	(5, 'Ravens', 'Baltimore', 'BAL', '@Ravens', '#Ravens'),
	(6, 'Bengals', 'Cincinnati', 'CIN', '@Bengals', '#Bengals'),
	(7, 'Browns', 'Cleveland', 'CLE', '@Browns', '#Browns'),
	(8, 'Steelers', 'Pittsburgh', 'PIT', '@Steelers', '#Steelers'),
	(9, 'Texans', 'Houston', 'HOU', '@HoustonTexans', '#Texans'),
	(10, 'Colts', 'Indianapolis', 'IND', '@Colts', '#Colts'),
	(11, 'Jaguars', 'Jacksonville', 'JAC', '@jaguars', '#Jaguars'),
	(12, 'Titans', 'Tennessee', 'TEN', '@TennesseeTitans', '#Titans'),
	(13, 'Broncos', 'Denver', 'DEN', '@Broncos', '#Broncos'),
	(14, 'Chiefs', 'Kansas City', 'KC', '@KCChiefs', '#Chiefs'),
	(15, 'Raiders', 'Oakland', 'OAK', '@Raiders', '#Raiders'),
	(16, 'Chargers', 'San Diego', 'SD', '@Chargers', '#Chargers'),
	(17, 'Cowboys', 'Dallas', 'DAL', '@dallascowboys', '#Cowboys'),
	(18, 'Giants', 'New York', 'NYG', '@Giants', '#Giants'),
	(19, 'Eagles', 'Philadelphia', 'PHI', '@Eagles', '#Eagles'),
	(20, 'Redskins', 'Washington', 'WAS', '@Redskins', '#Redskins'),
	(21, 'Bears', 'Chicago', 'CHI', '@ChicagoBears', '#Bears'),
	(22, 'Lions', 'Detroit', 'DET', '@DetroitLionsNFL', '#Lions'),
	(23, 'Packers', 'Green Bay', 'GB', '@Packers', '#Packers'),
	(24, 'Vikings', 'Minnesota', 'MIN', '@Vikings', '#Vikings'),
	(25, 'Falcons', 'Atlanta', 'ATL', '@Atlanta_Falcons', '#Falcons'),
	(26, 'Panthers', 'Carolina', 'CAR', '@Panthers', '#Panthers'),
	(27, 'Saints', 'New Orleans', 'NO', '@Saints', '#Saints'),
	(28, 'Buccaneers', 'Tampa Bay', 'TB', '@TBBuccaneers', '#Bucs'),
	(29, 'Cardinals', 'Arizona', 'ARI', '@AZCardinals', '#Cardinals'),
	(30, 'Rams', 'St. Louis', 'STL', '@STLouisRams', '#Rams'),
	(31, '49ers', 'San Francisco', 'SF', '@49ers', '#49ers'),
	(32, 'Seahawks', 'Seattle', 'SEA', '@Seahawks', '#Seahawks');