CREATE TABLE IF NOT EXISTS `nhlteams` (
  `TeamID` tinyint(4) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `City` varchar(50) NOT NULL,
  `DisplayName` varchar(50) NOT NULL,
  `TwitterAccount` varchar(50) DEFAULT NULL,
  `TwitterHashtag` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`TeamID`),
  KEY `IX_NHLTeams` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `nhlteams` (`TeamID`, `Name`, `City`, `DisplayName`, `TwitterAccount`, `TwitterHashtag`) VALUES
	(1, 'Ducks', 'Anaheim', 'ANA', '@AnaheimDucks', '#NHLDucks'),
	(2, 'Flames', 'Calgary', 'CGY', '@NHLFlames', '#Flames'),
	(3, 'Oilers', 'Edmonton', 'EDM', '@EdmontonOilers', '#Oilers'),
	(4, 'Kings', 'Los Angeles', 'LOS', '@LAKings', '#LAKings'),
	(5, 'Coyotes', 'Phoenix', 'PHX', '@phoenixcoyotes', '#Coyotes'),
	(6, 'Sharks', 'San Jose', 'SJS', '@SanJoseSharks', '#SJSharks'),
	(7, 'Canucks', 'Vancouver', 'VAN', '@VanCanucks', '#Canucks'),
	(8, 'Blackhawks', 'Chicago', 'CHI', '@NHLBlackhawks', '#Blackhawks'),
	(9, 'Avalanche', 'Colorado', 'COL', '@Avalanche', '#Avs'),
	(10, 'Stars', 'Dallas', 'DAL', '@DallasStars', '#Stars'),
	(11, 'Wild', 'Minnesota', 'MIN', '@mnwild', '#mnwild'),
	(12, 'Predators', 'Nashville', 'NSH', '@PredsNH', '#Preds'),
	(13, 'Blues', 'St. Louis', 'STL', '@StLouisBlues', '#stlblues'),
	(14, 'Jets', 'Winnipeg', 'WIN', '@NHLJets', '#NHLJets'),
	(15, 'Bruins', 'Boston', 'BOS', '@NHLBruins', '#NHLBruins'),
	(16, 'Sabres', 'Buffalo', 'BUF', '@BuffaloSabres', '#Sabres'),
	(17, 'Red Wings', 'Detroit', 'DET', '@DetroitRedWings', '#RedWings'),
	(18, 'Panthers', 'Florida', 'FLA', '@FlaPanthers', '#FlaPanthers'),
	(19, 'Canadiens', 'Montréal', 'MTL', '@CanadiensMTL', '#Habs'),
	(20, 'Senators', 'Ottawa', 'OTT', '@Senators', '#Sens'),
	(21, 'Lightning', 'Tampa Bay', 'TAM', '@TBLightning', '#TBLightning'),
	(22, 'Maple Leafs', 'Toronto', 'TOR', '@MapleLeafs', '#Leafs'),
	(23, 'Hurricanes', 'Carolina', 'CAR', '@NHLCanes', '#Canes'),
	(24, 'Blue Jackets', 'Columbus', 'CLB', '@BlueJacketsNHL', '#CBJ'),
	(25, 'Devils', 'New Jersey', 'NJD', '@NHLDevils', '#NJDevils'),
	(26, 'Islanders', 'New York', 'NYI', '@NYIslanders', '#Isles'),
	(27, 'Rangers', 'New York', 'NYR', '@NYRangers', '#NYR'),
	(28, 'Flyers', 'Philadelphia', 'PHI', '@NHLFlyers', '#Flyers'),
	(29, 'Penguins', 'Pittsburgh', 'PIT', '@penguins', '#Pens'),
	(30, 'Capitals', 'Washington', 'WAS', '@washcaps', '#Caps');